---
# Base playbook for cfme installation

#
# Dynamically create host groups based on distribution
#
- hosts: all
  tasks:
   - name: gather site specific fact data
     action: site_facts

   - name: group hosts by distribution
     action: group_by key={{ansible_distribution}}

#
# For RedHat hosts, register to RHN
#
- hosts: RedHat
  tasks:
   - include: tasks/rhn_register.yml
     when: rhn_method is defined

#
# For all other hosts, install CFME
#
- hosts: local
  vars_prompt:
  - name: "ipaddr"
    prompt: "Enter IP address of the machine which will be set up"
    private: no

  tasks:
   

  handlers:
   - include: handlers/restart_services.yml
