#
# if rhn_method == rhsm
#

- name: rhn_register | unregister from cert-based RHN
  redhat_subscription: state=absent
#  when: force_unregister is defined

- name: rhn_register | register and subscribe to cert-based RHN
  redhat_subscription: state=present username='$rhn_username' password='$rhn_password' autosubscribe='$autosubscribe' pool='$rhsm_pool' server_hostname='$rhsm_server_hostname' server_insecure='$rhsm_server_insecure' rhsm_baseurl='$rhsm_baseurl'
