- name: Squid install
  yum: name=squid state=latest

- name: Squid config copy
  copy: src=files/squid.conf dest=/etc/squid/squid.conf

- name: Squid passwords copy
  copy: src=files/passwords_basic dest=/etc/squid/passwords_basic

- name: Service start
  service: name=squid state=started

- name: Service enable
  service: name=squid enabled=yes